### ISSUE TITLE
Reporting rates All metrics not working

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#10]
Under Data > Data sets, selecting **All metrics** is not working. It should display all metrics for all data sets, but the list is empty. Applies to 2.23 and 2.24-SNAPSHOT.

![repo](https://cloud.githubusercontent.com/assets/908206/15575382/d46512e2-2352-11e6-940d-a9f169f72cf0.png)

**Comment by janhenrikoverland** [comment]
Fixed in 2.23 and 2.24-snapshot.
