### ISSUE TITLE
Favorite sort order alternating between ASC and DESC

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#11]
For the favorites dialog, when clicking Next multiple times, the sort order used in the request alternates between ASC and DESC. It should be always be ASC. Applies to 2.23 and 2.24-SNAPSHOT.

![asc](https://cloud.githubusercontent.com/assets/908206/15580537/63c5b6c4-2369-11e6-837b-721902a5abd4.png)

**Comment by janhenrikoverland** [comment]
Fixed:
2.24-snapshot
2.23
