### ISSUE TITLE
Fixed periods not displaying properly on restore from favorite

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#12]
Fixed periods are not displaying properly on restore from favorite.

Steps
---
- Create a table with monthly fixed periods
- Save as favorite
- Restore favorite
- Open period section

Applies to 2.23 and 2.24-SNAPSHOT.

![prev](https://cloud.githubusercontent.com/assets/908206/15583133/bd668c98-2374-11e6-978d-c8c860c80fdf.png)

**Comment by janhenrikoverland** [comment]
Fixed:
- 2.24 snapshot
- 2.23
