### ISSUE TITLE
Include showHierarchy param on direct download

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#13]
When using the direct download to CSV function (under Update), include the showHierarchy=true parameter in the analytics request.

?showHierarchy=true

This so that the server can provide the org unit hierarchy in the response.

**Comment by janhenrikoverland** [comment]
Fixed:
2.24-snapshot
2.23

**Comment by janhenrikoverland** [comment]
Also fixed for direct download to CSV.
