### ISSUE TITLE
Use table layout for direct download with all dimensions on rows

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#14]
1) In direct data download (under the Update button > CSV), request download in table layout where all dimensions are placed on rows. This by supplying a *rows* query parameter in the API request, where all dimensions are listed as rows, e.g.:

<pre>
&rows=dx;ou;pe
</pre>

The rationale is to provide as much information as possible when downloading data. I.e. when doing local analysis, one would like access to the codes, the org unit hierarchy, etc.

2) Remove "Meta data id scheme" sub-menu for direct download, and instead only offer CSV. When using table layout / rows, all types of identifiers are included so there is no purpose in having explicit id schemes for download.

![data](https://cloud.githubusercontent.com/assets/908206/15808874/d0cb4236-2b50-11e6-948c-18ed6ac48ceb.png)

**Comment by janhenrikoverland** [comment]
Fixed:
2.24-snapshot
2.23
