### ISSUE TITLE
Select multiple not working for all reporting rates

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#26]
Steps to reproduce
---
- Select Data > Data sets > All metrics
- Click Ctrl + some random reporting rates
- Click the the single arrow to select them

-> On first click, reporting rates are moved over to selected, but never removed from selected
-> On second click it crashes with JS error:

```ext-all.js:15 Uncaught TypeError: Cannot read property 'internalId' of undefined```

Applies to 2.23 and 2.24.

![dev](https://cloud.githubusercontent.com/assets/908206/16396161/b433e604-3cbd-11e6-8f76-1d79889522ad.png)

**Comment by janhenrikoverland** [comment]
Fixed:

- 2.24 snapshot
- 2.23
