### ISSUE TITLE
Reporting rates view all types option

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#3]
In Data > Data sets -> Metric drop-down. Add an option "All types" which lists each data set with the reporting rate, actual reports, expected reports options in the available section.

Often one would like to list data sets in a pivot in this order:

Data set A (reporting rate)
Data set A (actual reports)
Data set A (expected reports)
Data set B (reporting rate)
Data set B (actual reports)
Data set B (expected reports)

This is a bit inconvenient to select currently. This listing will make the selection easier.

**Comment by janhenrikoverland** [comment]
Fixed.
