### ISSUE TITLE
Title cell not covering total column

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#30]
The pivot table title cell is not spanning the total / right-most column, and instead leaves an empty area. This happens when there are more than one dimension on rows. It appears the title cell does not handle multiple dimensions on rows.

Can be reproduced on /demo here:

https://play.dhis2.org/demo/dhis-web-pivot/index.html?id=TrJlZ9y9fn5

![filter](https://cloud.githubusercontent.com/assets/908206/17211206/5c20aed4-54c8-11e6-84ec-9dfe628910c8.png)

**Comment by janhenrikoverland** [comment]
Fixed:

- 2.25 snapshot
- 2.24
