### ISSUE TITLE
Org unit hierarchy not reset when clicking new favorite

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#31]
The org unit hierarchy not reset when clicking new favorite.

Steps
---
- Load a favorite where all districts are selected in the org unit hierarchy.
- Click "New" under Favorites
- The org unit selection in the hierarchy is not reset to the root.

The root is selected by default when you open the app so it should be set back on new favorite.

**Comment by janhenrikoverland** [comment]
Fixed:
- 2.25
- 2.26 snapshot
