### ISSUE TITLE
Download as ID uses id scheme ID and not UID

### ISSUE THREAD

**Issue by mortenoh** [dhis2/dhis2-pivot#33]
When downloading "Json with ID", "XML with ID" etc, we need to use id scheme `UID` and not `ID` as this uses database identifiers.

This applies to not just the pivot, but other reporting apps as well.

**Comment by janhenrikoverland** [comment]
Fixed:

- 2.25 snapshot
- 2.24
- 2.23

Also fixed in data visualizer.
