### ISSUE TITLE
Sharing section in write interpretation dialog

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#34]
Integrate the "sharing" dialog into the "write interpretation" screen. It should be possible to define sharing for an interpretation. The sharing for an interpretation is based on on the sharing setting for the underlying favorite of the interpretation. One an interpretation is shared, the sharing setting for that favorite cannot be changed (for now).

Sharing needs to be enabled for interpretations on the server-side (quick fix).

**Comment by janhenrikoverland** [comment]
Implemented in 2.25 snapshot.
