### ISSUE TITLE
Raw data value set format download menu item

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#43]
Add an item in the downloads menu for raw data value format under `Download` > `Advanced` for:

- Data value set JSON
- Data value set XML

The data value set format works similarly as the regular analytics format, and is located at:

<pre>/api/analytics/dataValueSet</pre>

Documentation for analytics data value set format is [found here](http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_analytics.html#webapi_analytics_data_value_set_format).

**Comment by janhenrikoverland** [comment]
Implemented in 2.25 snapshot.
