### ISSUE TITLE
Update defaut values according to user choices

### ISSUE THREAD

**Issue by Aleglise** [dhis2/dhis2-pivot#44]
When accessing toPivot table the "12 months" relative period is always selected by default. 

It would be much more preferable to let admin set this default value or even better to save the last user choice instead of always proposing this "12 months" relative period.

This also apply to GIS & Data visualizer

**Comment by janhenrikoverland** [comment]
We have a system setting for this. Go to https://play.dhis2.org/demo/dhis-web-settings and look for "Default relative period for analysis".
