### ISSUE TITLE
Text in table is selected on click

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#45]
When left (and right)-clicking in the pivot table to open the "View as" dialog, the table content is highlighted-selected. It would be better if the text is not selected as you can easier see the content.

![pt](https://cloud.githubusercontent.com/assets/908206/18776377/2d52da8c-8169-11e6-99ca-d86bbec86b29.png)

**Comment by janhenrikoverland** [comment]
Fixed in 2.25 snapshot.
