### ISSUE TITLE
UI enhancements for Data/Pivot favorites menu

### ISSUE THREAD

**Issue by rachbrooke** [dhis2/dhis2-pivot#48]
Currently, we have: 
![favorites_new](https://cloud.githubusercontent.com/assets/17699575/19236862/eea3ccda-8ef9-11e6-8ee3-89bae885f962.png)

then:
![favorites_new2](https://cloud.githubusercontent.com/assets/17699575/19236880/0b4174dc-8efa-11e6-9402-7cae22124ba8.png)

I was hoping to see a new favorite, as per the menu indication Favorite > New

Instead, I get taken to a page explaining how to create a new pivot table.

The point I am trying to make is that the **new pivot table action** is hidden in **favorites** - or  **create a new favorite** is not working. 

If the current actions in the (favorites) menu should be here, grouped like this, then it might be worth renaming the favorites menu to something else like "Work with pivot tables" although this is too long for a menu title.

**Comment by larshelge** [comment]
This is a very common pattern for file editors.
