### ISSUE TITLE
Respect system setting for default digit group separator

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#5]
When rendering pivot tables, ensure that the system setting for default digit group separator is respected, both when rendering pivot tables, and when displaying the digit group separator drop-down under options. Default is SPACE is no setting has been set. The system setting key can be retrieved from: 

<pre>api/systemSettings/keyAnalysisDigitGroupSeparator</pre>

**Comment by janhenrikoverland** [comment]
Implemented

**Comment by larshelge** [comment]
Back-porting this feature to 2.23 would be useful.

**Comment by janhenrikoverland** [comment]
Backported to 2.23
