### ISSUE TITLE
Org units have undefined order on select by level

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#8]
When selecting organisation units by level and having org unit dimension on columns (or rows), the ordering is undefined / random. Seems to only apply when root level (e.g. Sierra Leone in demo db) is selected as boundary. Applies to 2.23 and trunk.

The org units should be ordered by according to the hierarchy, then alphabetically with each parent. This was the behavior in 2.22.

### Steps to reproduce
- Select organisation units by level -> facility level
- Put organisation unit on columns
- Put data and periods on columns and render table.

![pivot](https://cloud.githubusercontent.com/assets/908206/15540248/a0a6945c-2286-11e6-9ab2-bf94c773fdac.png)

**Comment by janhenrikoverland** [comment]
Invalid.

This works as expected. In the reported screenshot "Panderu MCHP" comes first because the name has a leading space. Screenshot below.

![screenshot from 2016-05-27 22 50 19](https://cloud.githubusercontent.com/assets/1010094/15620920/9affe76e-245d-11e6-8461-a62105d871d9.png)
