### ISSUE TITLE
Show hierarchy param not included on download with table layout

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-pivot#9]
When doing a Download > Table layout and the "Show hierarchy" option is checked, the query parameter <pre>showHierarchy=true</pre> must be included in the analytics API request URL. This so that the analytics response can include the org unit hierarchy. This applies also to the download under Update > CSV as well. Not happening per 2.23 and 2.24-SNAPSHOT.

**Comment by janhenrikoverland** [comment]
Fixed:
2.24-snapshot
2.23
